/**
 * Clothing categories, types, styles, seasons, and occasions
 */

export const CLOTHING_TYPES = [
  { id: 'tshirt', label: 'T-Shirt', category: 'tops', icon: '👕', emoji: '👕' },
  { id: 'shirt', label: 'Shirt', category: 'tops', icon: '👔', emoji: '👔' },
  { id: 'blouse', label: 'Blouse', category: 'tops', icon: '👚', emoji: '👚' },
  { id: 'sweater', label: 'Sweater', category: 'tops', icon: '🧥', emoji: '🧥' },
  { id: 'hoodie', label: 'Hoodie', category: 'tops', icon: '🧥', emoji: '🧥' },
  { id: 'tank_top', label: 'Tank Top', category: 'tops', icon: '👕', emoji: '👕' },
  { id: 'crop_top', label: 'Crop Top', category: 'tops', icon: '👕', emoji: '👕' },
  { id: 'pants', label: 'Pants', category: 'bottoms', icon: '👖', emoji: '👖' },
  { id: 'jeans', label: 'Jeans', category: 'bottoms', icon: '👖', emoji: '👖' },
  { id: 'shorts', label: 'Shorts', category: 'bottoms', icon: '🩳', emoji: '🩳' },
  { id: 'skirt', label: 'Skirt', category: 'bottoms', icon: '👗', emoji: '👗' },
  { id: 'leggings', label: 'Leggings', category: 'bottoms', icon: '👖', emoji: '👖' },
  { id: 'dress', label: 'Dress', category: 'dresses', icon: '👗', emoji: '👗' },
  { id: 'jumpsuit', label: 'Jumpsuit', category: 'dresses', icon: '👗', emoji: '👗' },
  { id: 'romper', label: 'Romper', category: 'dresses', icon: '👗', emoji: '👗' },
  { id: 'jacket', label: 'Jacket', category: 'outerwear', icon: '🧥', emoji: '🧥' },
  { id: 'coat', label: 'Coat', category: 'outerwear', icon: '🧥', emoji: '🧥' },
  { id: 'blazer', label: 'Blazer', category: 'outerwear', icon: '🧥', emoji: '🧥' },
  { id: 'cardigan', label: 'Cardigan', category: 'outerwear', icon: '🧥', emoji: '🧥' },
  { id: 'vest', label: 'Vest', category: 'outerwear', icon: '🦺', emoji: '🦺' },
  { id: 'sneakers', label: 'Sneakers', category: 'shoes', icon: '👟', emoji: '👟' },
  { id: 'boots', label: 'Boots', category: 'shoes', icon: '👢', emoji: '👢' },
  { id: 'heels', label: 'Heels', category: 'shoes', icon: '👠', emoji: '👠' },
  { id: 'flats', label: 'Flats', category: 'shoes', icon: '🥿', emoji: '🥿' },
  { id: 'sandals', label: 'Sandals', category: 'shoes', icon: '👡', emoji: '👡' },
  { id: 'loafers', label: 'Loafers', category: 'shoes', icon: '🥾', emoji: '🥾' },
  { id: 'oxfords', label: 'Oxfords', category: 'shoes', icon: '👞', emoji: '👞' },
  { id: 'hat', label: 'Hat', category: 'accessories', icon: '🧢', emoji: '🧢' },
  { id: 'scarf', label: 'Scarf', category: 'accessories', icon: '🧣', emoji: '🧣' },
  { id: 'belt', label: 'Belt', category: 'accessories', icon: '👜', emoji: '👜' },
  { id: 'bag', label: 'Bag', category: 'accessories', icon: '👜', emoji: '👜' },
  { id: 'jewelry', label: 'Jewelry', category: 'accessories', icon: '💍', emoji: '💍' },
  { id: 'sunglasses', label: 'Sunglasses', category: 'accessories', icon: '🕶️', emoji: '🕶️' },
  { id: 'sports_top', label: 'Sports Top', category: 'activewear', icon: '🏃', emoji: '🏃' },
  { id: 'sports_bottom', label: 'Sports Bottom', category: 'activewear', icon: '🏃', emoji: '🏃' },
  { id: 'tracksuit', label: 'Tracksuit', category: 'activewear', icon: '🏃', emoji: '🏃' },
  { id: 'suit', label: 'Suit', category: 'formalwear', icon: '🤵', emoji: '🤵' },
  { id: 'formal_dress', label: 'Formal Dress', category: 'formalwear', icon: '👗', emoji: '👗' },
  { id: 'other', label: 'Other', category: 'other', icon: '👔', emoji: '👔' },
];

export const CLOTHING_CATEGORIES = [
  { id: 'all', label: 'All', icon: '✨' },
  { id: 'tops', label: 'Tops', icon: '👕' },
  { id: 'bottoms', label: 'Bottoms', icon: '👖' },
  { id: 'dresses', label: 'Dresses', icon: '👗' },
  { id: 'outerwear', label: 'Outerwear', icon: '🧥' },
  { id: 'shoes', label: 'Shoes', icon: '👟' },
  { id: 'accessories', label: 'Accessories', icon: '👜' },
  { id: 'activewear', label: 'Activewear', icon: '🏃' },
  { id: 'formalwear', label: 'Formalwear', icon: '🤵' },
];

export const COLORS_LIST = [
  { id: 'white', label: 'White', hex: '#FFFFFF', colorGroup: 'neutral' },
  { id: 'black', label: 'Black', hex: '#1A1A1A', colorGroup: 'neutral' },
  { id: 'gray', label: 'Gray', hex: '#9E9E9E', colorGroup: 'neutral' },
  { id: 'beige', label: 'Beige', hex: '#D4B896', colorGroup: 'neutral' },
  { id: 'navy', label: 'Navy', hex: '#1B2A4A', colorGroup: 'cool' },
  { id: 'blue', label: 'Blue', hex: '#4A90D9', colorGroup: 'cool' },
  { id: 'light_blue', label: 'Light Blue', hex: '#87CEEB', colorGroup: 'cool' },
  { id: 'red', label: 'Red', hex: '#C0392B', colorGroup: 'warm' },
  { id: 'pink', label: 'Pink', hex: '#E8A0A0', colorGroup: 'warm' },
  { id: 'hot_pink', label: 'Hot Pink', hex: '#FF69B4', colorGroup: 'warm' },
  { id: 'orange', label: 'Orange', hex: '#E8894A', colorGroup: 'warm' },
  { id: 'yellow', label: 'Yellow', hex: '#F5D05E', colorGroup: 'warm' },
  { id: 'green', label: 'Green', hex: '#4A9B6F', colorGroup: 'cool' },
  { id: 'olive', label: 'Olive', hex: '#8A9B4A', colorGroup: 'neutral' },
  { id: 'mint', label: 'Mint', hex: '#A8D8B0', colorGroup: 'cool' },
  { id: 'purple', label: 'Purple', hex: '#8B5CF6', colorGroup: 'cool' },
  { id: 'lavender', label: 'Lavender', hex: '#C4B5FD', colorGroup: 'cool' },
  { id: 'brown', label: 'Brown', hex: '#795548', colorGroup: 'neutral' },
  { id: 'tan', label: 'Tan', hex: '#C4A882', colorGroup: 'neutral' },
  { id: 'camel', label: 'Camel', hex: '#C19A6B', colorGroup: 'neutral' },
  { id: 'cream', label: 'Cream', hex: '#FFFDD0', colorGroup: 'neutral' },
  { id: 'burgundy', label: 'Burgundy', hex: '#800020', colorGroup: 'warm' },
  { id: 'teal', label: 'Teal', hex: '#008080', colorGroup: 'cool' },
  { id: 'coral', label: 'Coral', hex: '#FF6B6B', colorGroup: 'warm' },
  { id: 'mustard', label: 'Mustard', hex: '#FFDB58', colorGroup: 'warm' },
  { id: 'multicolor', label: 'Multicolor', hex: '#GRADIENT', colorGroup: 'special' },
];

export const PATTERNS = [
  { id: 'solid', label: 'Solid' },
  { id: 'striped', label: 'Striped' },
  { id: 'plaid', label: 'Plaid' },
  { id: 'floral', label: 'Floral' },
  { id: 'graphic', label: 'Graphic' },
  { id: 'abstract', label: 'Abstract' },
  { id: 'animal_print', label: 'Animal Print' },
  { id: 'polka_dot', label: 'Polka Dot' },
  { id: 'geometric', label: 'Geometric' },
  { id: 'camouflage', label: 'Camouflage' },
  { id: 'tie_dye', label: 'Tie-Dye' },
  { id: 'houndstooth', label: 'Houndstooth' },
  { id: 'other', label: 'Other' },
];

export const STYLES = [
  { id: 'casual', label: 'Casual', icon: '😊' },
  { id: 'formal', label: 'Formal', icon: '🤵' },
  { id: 'business', label: 'Business', icon: '💼' },
  { id: 'sporty', label: 'Sporty', icon: '🏃' },
  { id: 'streetwear', label: 'Streetwear', icon: '🔥' },
  { id: 'bohemian', label: 'Bohemian', icon: '🌸' },
  { id: 'minimalist', label: 'Minimalist', icon: '⬜' },
  { id: 'preppy', label: 'Preppy', icon: '🎓' },
  { id: 'vintage', label: 'Vintage', icon: '⏰' },
  { id: 'romantic', label: 'Romantic', icon: '💕' },
  { id: 'edgy', label: 'Edgy', icon: '⚡' },
  { id: 'classic', label: 'Classic', icon: '✨' },
];

export const SEASONS = [
  { id: 'all', label: 'All Season', icon: '🌍' },
  { id: 'spring', label: 'Spring', icon: '🌸' },
  { id: 'summer', label: 'Summer', icon: '☀️' },
  { id: 'fall', label: 'Fall', icon: '🍂' },
  { id: 'winter', label: 'Winter', icon: '❄️' },
];

export const OCCASIONS = [
  { id: 'casual', label: 'Casual', icon: '😊', description: 'Everyday wear' },
  { id: 'work', label: 'Work', icon: '💼', description: 'Office or business' },
  { id: 'date', label: 'Date Night', icon: '💕', description: 'Romantic outing' },
  { id: 'formal', label: 'Formal', icon: '🎩', description: 'Gala or ceremony' },
  { id: 'gym', label: 'Gym', icon: '💪', description: 'Working out' },
  { id: 'outdoor', label: 'Outdoor', icon: '🌿', description: 'Hiking or nature' },
  { id: 'beach', label: 'Beach', icon: '🏖️', description: 'Beach or pool' },
  { id: 'party', label: 'Party', icon: '🎉', description: 'Celebration or social' },
  { id: 'travel', label: 'Travel', icon: '✈️', description: 'Comfortable travel' },
  { id: 'brunch', label: 'Brunch', icon: '🥂', description: 'Brunch or lunch' },
];

export const WEATHER = [
  { id: 'hot', label: 'Hot', icon: '🌞', temp: '80°F+' },
  { id: 'warm', label: 'Warm', icon: '☀️', temp: '65-80°F' },
  { id: 'mild', label: 'Mild', icon: '🌤️', temp: '50-65°F' },
  { id: 'cool', label: 'Cool', icon: '🌥️', temp: '40-50°F' },
  { id: 'cold', label: 'Cold', icon: '❄️', temp: '32-40°F' },
  { id: 'freezing', label: 'Freezing', icon: '🥶', temp: 'Below 32°F' },
  { id: 'rainy', label: 'Rainy', icon: '🌧️', temp: 'Any temp' },
  { id: 'snowy', label: 'Snowy', icon: '❄️', temp: 'Below 35°F' },
];

export default {
  CLOTHING_TYPES,
  CLOTHING_CATEGORIES,
  COLORS_LIST,
  PATTERNS,
  STYLES,
  SEASONS,
  OCCASIONS,
  WEATHER,
};
